title: RombiTech Docs
description: Technical Guides & Support
theme: just-the-docs

url: https://docs.rombitech.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-polyglot

languages: ["en", "zh", "es"]
default_lang: "en"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true

sass:
  sourcemap: never # By disabling source map generation, you avoid the specific conflict points that arise when jekyll-polyglot iterates through the build process for each language
