title: RombiTech Docs
description: Technical Guides & Support
theme: just-the-docs

url: https://docs.rombitech.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-polyglot
